### ISSUE TITLE
Why hmatrix-gsl needs gsl-0

### ISSUE THREAD

**Issue by chenyulue** [haskell-numerics/hmatrix#312]
I wonder why `hmatrix-gsl` needs `gsl-0` library. Actually, in msys2, after running `pacman -S mingw-w64-x86_64-gsl`, the lib installed is `gsl`, not `gsl-0`. 

If I download the source files, edit `hmatrix-gsl.cabal` and change the `gsl-0` reference to `gsl`, the following error occurs:

<details>

```
hmatrix-gsl-0.19.0.0: copy/register
Installing library in C:\Users\{my name}\hmatrix\packages\gsl\.stack-work\install\f7aa4a34\lib\x86_64-windows-ghc-8.6.5\hmatrix-gsl-0.19.0.0-DJciqu5BI0GLZgpPyo8VNH
Registering library for hmatrix-gsl-0.19.0.0..
Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.5.exe:
'C:\Users\{my name}\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.EXE'
exited with an error:
hmatrix-gsl-0.19.0.0: Warning: haddock-interfaces:
C:\Users\{my name}\hmatrix\packages\gsl\.stack-work\install\f7aa4a34\doc\hmatrix-gsl-0.19.0.0\hmatrix-gsl.haddock
doesn't exist or isn't a file
hmatrix-gsl-0.19.0.0: library-dirs: /usr/local/lib is a relative path which
makes no sense (as there is nothing for it to be relative to). You can make
paths relative to the package database itself by using ${pkgroot}. (use
--force to override)
hmatrix-gsl-0.19.0.0: dynamic-library-dirs: /usr/local/lib is a relative path
which makes no sense (as there is nothing for it to be relative to). You can
make paths relative to the package database itself by using ${pkgroot}. (use
--force to override)


--  While building package hmatrix-gsl-0.19.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.5.exe --builddir=.stack-work\dist\e626a42b register
    Process exited with code: ExitFailure 1
```

</details>

I have no idea about this error.

**Comment by mpilgrem** [comment]
I think this is resolved by https://github.com/haskell-numerics/hmatrix/pull/332.

**Comment by alex404** [comment]
As of now hmatrix-gsl on both hackage and stackage still can't compile on windows because of this. Is there any reason hmatrix-gsl and hmatrix-special on hackage and stackage haven't been updated in a while? If there's any bottlenecks there I'd be happy to help.
